const String path = "assets/images/";

const List<Map<String, dynamic>> localImageData = [
  {
    'imageUrl': "${path}ilustration.jpg",
    'name': 'Sunset',
    'likes': 120,
    'author': 'John Doe',
    'source': 'Unsplash',
    'description': 'A beautiful sunset over the mountains.',
    'date': '2023-01-01',
    'location': 'Rocky Mountains, USA',
    'camera': 'Canon EOS 5D Mark IV',
    },
    {
    'imageUrl': "${path}ilustration1.jpg",
    'name': 'Forest',
    'likes': 98,
    'author': 'Jane Smith',
    'source': 'Pexels',
    'description': 'A serene forest with tall trees.',
    'date': '2023-02-15',
    'location': 'Black Forest, Germany',
    'camera': 'Nikon D850',
    },
    {
    'imageUrl': "${path}ilustration2.jpg",
    'name': 'Mountain',
    'likes': 150,
    'author': 'Mike Johnson',
    'source': 'Pixabay',
    'description': 'A majestic mountain covered in snow.',
    'date': '2023-03-10',
    'location': 'Alps, Switzerland',
    'camera': 'Sony Alpha 7R IV',
    },
    {
    'imageUrl': "${path}ilustration3.jpg",
    'name': 'Ocean',
    'likes': 200,
    'author': 'Emily Davis',
    'source': 'Unsplash',
    'description': 'A vast ocean with clear blue water.',
    'date': '2023-04-05',
    'location': 'Pacific Ocean',
    'camera': 'Fujifilm X-T4',
    },
    {
    'imageUrl': "${path}ilustration4.jpg",
    'name': 'City',
    'likes': 175,
    'author': 'Chris Brown',
    'source': 'Pexels',
    'description': 'A bustling city skyline at night.',
    'date': '2023-05-20',
    'location': 'New York City, USA',
    'camera': 'Canon EOS R5',
    },
    {
    'imageUrl': "${path}ilustration5.jpg",
    'name': 'Desert',
    'likes': 85,
    'author': 'Anna White',
    'source': 'Pixabay',
    'description': 'A vast desert with rolling sand dunes.',
    'date': '2023-06-15',
    'location': 'Sahara Desert, Africa',
    'camera': 'Nikon Z7 II',
    },
    {
    'imageUrl': "${path}ilustration6.jpg",
    'name': 'River',
    'likes': 110,
    'author': 'David Wilson',
    'source': 'Unsplash',
    'description': 'A calm river flowing through a forest.',
    'date': '2023-07-10',
    'location': 'Amazon River, Brazil',
    'camera': 'Sony A7 III',
    },
    {
    'imageUrl': "${path}ilustration7.jpg",
    'name': 'Sky',
    'likes': 95,
    'author': 'Laura Moore',
    'source': 'Pexels',
    'description': 'A clear sky with a few clouds.',
    'date': '2023-08-05',
    'location': 'Great Plains, USA',
    'camera': 'Canon EOS 90D',
    },
    {
    'imageUrl': "${path}ilustration8.jpg",
    'name': 'Beach',
    'likes': 130,
    'author': 'Robert Taylor',
    'source': 'Pixabay',
    'description': 'A sunny beach with golden sand.',
    'date': '2023-09-01',
    'location': 'Maldives',
    'camera': 'Nikon D750',
    },
];
