const String path = "assets/images/";

const List<Map<String, dynamic>> localImageData = [
  {
    'imageUrl': "${path}ilustration.jpg",
    'name': 'Sunset',
    'likes': 120,
    'author': 'John Doe',
    'source': 'Unsplash',
    'description': 'A beautiful sunset over the mountains.',
    'date': '2023-01-01',
    'location': 'Rocky Mountains, USA',
    'camera': 'Canon EOS 5D Mark IV',
    },
    {
    'imageUrl': "${path}ilustration1.jpg",
    'name': 'Forest',
    'likes': 98,
    'author': 'Jane Smith',
    'source': 'Pexels',
    'description': 'A serene forest with tall trees.',
    'date': '2023-02-15',
    'location': 'Black Forest, Germany',
    'camera': 'Nikon D850',
    },
    {
    'imageUrl': "${path}ilustration2.jpg",
    'name': 'Mountain',
    'likes': 150,
    'author': 'Mike Johnson',
    'source': 'Pixabay',
    'description': 'A majestic mountain covered in snow.',
    'date': '2023-03-10',
    'location': 'Alps, Switzerland',
    'camera': 'Sony Alpha 7R IV',
    },
    {
    'imageUrl': "${path}ilustration3.jpg",
    'name': 'Ocean',
    'likes': 200,
    'author': 'Emily Davis',
    'source': 'Unsplash',
    'description': 'A vast ocean with clear blue water.',
    'date': '2023-04-05',
    'location': 'Pacific Ocean',
    'camera': 'Fujifilm X-T4',
    },
    {
    'imageUrl': "${path}ilustration4.jpg",
    'name': 'City',
    'likes': 175,
    'author': 'Chris Brown',
    'source': 'Pexels',
    'description': 'A bustling city skyline at night.',
    'date': '2023-05-20',
    'location': 'New York City, USA',
    'camera': 'Canon EOS R5',
    },
    {
    'imageUrl': "${path}ilustration5.jpg",
    'name': 'Desert',
    'likes': 85,
    'author': 'Anna White',
    'source': 'Pixabay',
    'description': 'A vast desert with rolling sand dunes.',
    'date': '2023-06-15',
    'location': 'Sahara Desert, Africa',
    'camera': 'Nikon Z7 II',
    },
    {
    'imageUrl': "${path}ilustration6.jpg",
    'name': 'River',
    'likes': 110,
    'author': 'David Wilson',
    'source': 'Unsplash',
    'description': 'A calm river flowing through a forest.',
    'date': '2023-07-10',
    'location': 'Amazon River, Brazil',
    'camera': 'Sony A7 III',
    },
    {
    'imageUrl': "${path}ilustration7.jpg",
    'name': 'Sky',
    'likes': 95,
    'author': 'Laura Moore',
    'source': 'Pexels',
    'description': 'A clear sky with a few clouds.',
    'date': '2023-08-05',
    'location': 'Great Plains, USA',
    'camera': 'Canon EOS 90D',
    },
    {
    'imageUrl': "${path}ilustration8.jpg",
    'name': 'Beach',
    'likes': 130,
    'author': 'Robert Taylor',
    'source': 'Pixabay',
    'description': 'A sunny beach with golden sand.',
    'date': '2023-09-01',
    'location': 'Maldives',
    'camera': 'Nikon D750',
    },
    {
      'imageUrl': "${path}ilustration9.jpg",
      'name': 'Waterfall',
      'likes': 140,
      'author': 'Sophia Martinez',
      'source': 'Unsplash',
      'description': 'A stunning waterfall in a tropical forest.',
      'date': '2023-10-01',
      'location': 'Iguazu Falls, Argentina',
      'camera': 'Canon EOS 6D Mark II',
    },
    {
      'imageUrl': "${path}ilustration10.jpg",
      'name': 'Canyon',
      'likes': 115,
      'author': 'James Anderson',
      'source': 'Pexels',
      'description': 'A deep canyon with red rock formations.',
      'date': '2023-11-15',
      'location': 'Grand Canyon, USA',
      'camera': 'Nikon D5600',
    },
    {
      'imageUrl': "${path}ilustration11.jpg",
      'name': 'Lake',
      'likes': 125,
      'author': 'Olivia Brown',
      'source': 'Pixabay',
      'description': 'A tranquil lake surrounded by mountains.',
      'date': '2023-12-10',
      'location': 'Lake Tahoe, USA',
      'camera': 'Sony A6400',
    },
    {
      'imageUrl': "${path}ilustration12.jpg",
      'name': 'Valley',
      'likes': 105,
      'author': 'Liam Wilson',
      'source': 'Unsplash',
      'description': 'A lush valley with a river running through it.',
      'date': '2024-01-05',
      'location': 'Yosemite Valley, USA',
      'camera': 'Fujifilm X100V',
    },
    {
      'imageUrl': "${path}ilustration13.jpg",
      'name': 'Glacier',
      'likes': 135,
      'author': 'Emma Johnson',
      'source': 'Pexels',
      'description': 'A massive glacier with blue ice.',
      'date': '2024-02-20',
      'location': 'Vatnajökull, Iceland',
      'camera': 'Canon EOS M50',
    },
    {
      'imageUrl': "${path}ilustration14.jpg",
      'name': 'Volcano',
      'likes': 145,
      'author': 'Noah Davis',
      'source': 'Pixabay',
      'description': 'An active volcano spewing lava.',
      'date': '2024-03-15',
      'location': 'Mount Etna, Italy',
      'camera': 'Nikon D7200',
    }
];
